config/routes.rb
Rails.application.routes.draw do
  match 'auth/:provider/callback',
    :to => 'sessions#create',
    :via => [:get, :post]

  match 'signout',
    :to => 'sessions#destroy',
    :as => 'signout',
    :via => [:get, :post]

  resources :questions

  match 'mine',
    :to => 'questions#mine',
    :as => 'my_questions',
    :via => :get

  match 'favorite',
    :to => 'questions#favorite',
    :as => 'favorite_questions',
    :via => :get

  match 'by/:email',
    :email => /.*/,
    :to => 'questions#by',
    :as => 'questions_by',
    :via => :get

  match 'favorited_by/:email',
    :email => /.*/,
    :to => 'questions#favorited_by',
    :as => 'questions_favorited_by',
    :via => :get

  resources :likes, :only => [:create, :destroy]

  root :to => 'application#index'
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  validates :user,
    :presence => true,
    :uniqueness => { :scope => :question_id }

  validates :question,
    :presence => true,
    :uniqueness => { :scope => :user_id }
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :likes

  validates :user,
    :presence => true

  validates :description,
    :presence => true,
    :length => { :maximum => 140 } 

  acts_as_taggable

  before_save :downcase_tags

  private
  
  def downcase_tags
    self.tag_list = self.tag_list.map(&:downcase)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions, :dependent => :destroy
  has_many :likes, :dependent => :destroy
  has_many :favorites, :through => :likes, :source => :question

  validates :email,
    :presence => true,
    :email => true,
    :uniqueness => true,
    :format => /@thoughtworks\.com/

  def self.from_omniauth(auth)
    email = auth[:extra][:raw_info][:email]
    where(:email => email).first_or_initialize.tap do |user|
      user.email = email
      user.save!
    end
  end

  def username
    email.split('@').first
  end

  def likes?(question)
    likes.where(:question => question).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :forbid!

  def index
    redirect_to questions_path if current_user
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate!
    return if current_user 
    #redirect_to("/auth/saml?redirectUrl=#{URI::encode(request.path)}")
    original = request.env['HTTP_REFERER']
    redirect_to(root_path, :redirectUrl => request.path)
  end

  def forbid!
    render :status => :forbidden, 
      :text => 'You do not have rights to perform this operation.'
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_filter :authenticate!

  def create
    q = Question.find(params[:question_id])
    like = Like.new(:user => current_user, :question => q)
    flash[:success] = 'Question added to your favorites.' if like.save
    redirect_to(request.referer || root_path)
  end

  def destroy
    like = Like.find(params[:id])
    return forbid! unless like.user == current_user
    like.destroy
    flash[:notice] = 'Question removed from your favorites.'
    redirect_to(request.referer || root_path)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate!

  def index
    @questions = build_question_list
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new
    @question.user = current_user
    @question.description = params[:question][:description]
    @question.tag_list = params[:question][:tag_list]
    if @question.save
      flash[:success] = 'Question added.'
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
    return forbid! unless @question.user == current_user
  end

  def update
    @question = Question.find(params[:id])
    return forbid! unless @question.user == current_user
    @question.description = params[:question][:description]
    @question.tag_list = params[:question][:tag_list]
    if @question.save
      flash[:success] = 'Question updated.'
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    q = Question.find(params[:id])
    return forbid! unless q.user == current_user
    q.destroy
    flash[:notice] = 'Question removed.'
    redirect_to questions_path
  end

  def mine
    @questions = build_question_list(current_user.questions)
    render :index
  end

  def favorite
    @questions = build_question_list(current_user.favorites)
    render :index
  end

  def by
    @questions = build_question_list(User.find_by_email(params[:email]).questions)
    render :index
  end

  def favorited_by
    @questions = build_question_list(User.find_by_email(params[:email]).favorites)
    render :index
  end

  private

  def build_question_list(scope=Question)
    apply_pagination(apply_order(apply_tags(scope)))
  end

  def apply_pagination(scope)
    scope.paginate(:page => params[:page], :per_page => 30)
  end

  def apply_order(scope)
    scope.order(:created_at => :desc)
  end

  def apply_tags(scope)
    return scope unless params[:tag_filter]
    tags = params[:tag_filter].downcase.split(',')
    scope.tagged_with(tags, :any => true)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => 'Signed out successfuly.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def popular_tags
    @popular_tags ||= ActsAsTaggableOn::Tag.most_used(10)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def like_or_dislike(question)
    like = current_user.likes.where(:question => question).first
    if like
      {
        :path => like_path(like),
        :method => :delete,
        :class => 'liked'
      }
    else
      {
        :path => likes_path(:question_id => question.id),
        :method => :create,
        :class => ''
      }
    end
  end
end

app/views/application/index.html.erb
<div class="well-lg text-center">
  <%= link_to '/auth/google_oauth2', :id => 'sign_in', :class => 'btn btn-info btn-lg' do %>
    <span class="fa fa-google-plus fa-lg"></span>
    <span>Sign in with Google</span>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ask</title>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.0/lumen/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/select2/3.5.2/select2.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" />

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/select2/3.5.2/select2.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">

      <div class="navbar-header">
        <button type="button"
          class="navbar-toggle collapsed" 
          data-toggle="collapse" 
          data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <span class="navbar-brand">
          <strong>Ask</strong>
        </span>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if current_user %>
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if request.env['PATH_INFO'] == questions_path && !params[:tag_filter] %>">
              <a href="<%= root_path %>">
                <span class="glyphicon glyphicon-home"></span>
                &nbsp;
                <span>Home</span>
              </a>
            </li>
            <li class="<%= 'active' if request.env['PATH_INFO'] == my_questions_path %>">
              <a href="<%= my_questions_path %>">
                <span class="glyphicon glyphicon-user"></span>
                &nbsp;
                <span>My Questions</span>
              </a>
            </li>
            <li class="<%= 'active' if request.env['PATH_INFO'] == favorite_questions_path %>">
              <a href="<%= favorite_questions_path %>">
                <span class="glyphicon glyphicon-heart"></span>
                &nbsp;
                <span>Favorite</span>
              </a>
            </li>
          </ul>

          <%= form_tag(questions_path, :method => 'get', :class => 'navbar-form navbar-left', :role => 'search') do %>
            <%= text_field_tag(:tag_filter, params[:tag_filter], :placeholder => 'Tags') %>
            <%= button_tag(:type => 'submit', :class => 'btn btn-default') do %>
              <span class="glyphicon glyphicon-search"></span>
            <% end %>
          <% end %>

          <div class="nav navbar-nav nav-add-question">
            <%= link_to new_question_path, :class => 'btn btn-info btn-sm' do %>
              <span class="glyphicon glyphicon-plus"></span>
              &nbsp;
              <span>Add Question</span>
            <% end %>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                <%= gravatar_image_tag current_user.email,
                  :alt => current_user.username,
                  :title => current_user.username,
                  :class => 'img-circle',
                  :gravatar => { :secure => true, :size => 17 }
                %>
                &nbsp;
                <span class="current-user"><%= current_user.username %></span>
                <span class="caret"></span>
                </a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to signout_path do %>
                    <span class="glyphicon glyphicon-log-out"></span> <span>Sign Out</span>
                  <% end %>
                </li>
              </ul>
            </li>
          </ul>
        <% end %>
      </div><!-- /.navbar-collapse -->

    </div><!-- container-fluid -->
  </nav>

  <main>

    <% if flash[:success] %>
      <section class="row container col-xs-12">
        <div id="flash" class="alert alert-success alert-dismissible col-md-4 col-md-offset-4" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
          </button>
          <span class="glyphicon glyphicon-info-sign"></span>
          &nbsp;
          <span><%= flash[:success] %></span>
        </div>
      </section>
    <% end %>

    <% if flash[:notice] %>
      <section class="row container col-xs-12">
        <div id="flash" class="alert alert-warning alert-dismissible col-md-4 col-md-offset-4" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
          </button>
          <span class="glyphicon glyphicon-info-sign"></span>
          &nbsp;
          <span><%= flash[:notice] %></span>
        </div>
      </section>
    <% end %>

    <div class="col-xs-12">
      <%= yield %>
    </div>
  </main>

  <footer class="col-xs-12">
    <hr />
  </footer>

  <script type="text/javascript">
    $(function() {
      $("[rel='tooltip']").tooltip();

      var popularTags = '<%= popular_tags.join(',') %>'.split(',');

      $('#question_tag_list')
        .select2({
          tags: popularTags,
          maximumSelectionSize: 3
        })
        .select2('container')
        .find('ul.select2-choices')
        .addClass('form-control');

      $('#tag_filter')
        .select2({
          tags: popularTags,
          maximumSelectionSize: 3
        })
        .select2('container')
        .find('ul.select2-choices')
        .addClass('form-control');
    });
  </script>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question,
  :url => url,
  :method => method,
  :html => {
    :class => 'row col-sm-10 col-md-8',
    :role => 'form'
  }) do |f| %>

  <fieldset>
    <legend>
      <%= method == 'post' ? 'New Question' : 'Edit Question' %>
    </legend>

    <p class='form-group'>
      <%= f.text_area :description,
        :rows => 4,
        :autofocus => true,
        :required => true,
        :maxlength => '140',
        :placeholder => 'Your question...',
        :class => 'form-control' %>
    </p>

    <p class='form-group'>
      <%= f.text_field :tag_list, :placeholder => 'Tags', :value => @question.tag_list.join(',')  %>
    </p>

    <p class='form-group'>
      <%= button_tag :type => 'submit',
        :class => 'btn btn-success btn-sm' do %>
        <span class="glyphicon glyphicon-ok"></span>
        <span>Save</span>
      <% end %>

      <%= link_to back, :class => 'btn btn-warning btn-sm' do %>
        <span class="glyphicon glyphicon-remove"></span>
        <span>Cancel</span>
      <% end %>
    </p>
  </fieldset>
<% end %>

app/views/questions/edit.html.erb
<%= render 'form',
  :url => question_path(@question),
  :method => 'put',
  :back => question_path(@question)
%>

app/views/questions/index.html.erb
<ul class="row list-unstyled">
  <% @questions.each do |q| %>
    <li class="col-sm-6 col-lg-4">
      <section class="panel panel-default">
        <hr />
        <blockquote class="panlel-body question-text">
          <em class="lead">
            <%= link_to q.description, question_path(q) %>
        </em>
        </blockquote>
        <footer class="clearfix panel-footer text-center">
          <%= gravatar_image_tag q.user.email,
            :class => 'img-circle pull-left',
            :rel => 'tooltip',
            'data-toggle' => 'tooltip',
            'data-placement' => 'bottom',
            :title => '',
            'data-original-title' => q.user.username,
            :gravatar => { :secure => true, :size => 30 }
          %>

          <% like_config = like_or_dislike(q) %>
          <%= link_to(like_config[:path], :method => like_config[:method],
           :class => "pull-right like #{like_config[:class]}") do %>
            <span
              class="glyphicon glyphicon-heart"
              rel="tooltip"
              data-toggle="tooltip"
              data-placement="bottom"
              title=""
              data-original-title="<%= q.likes.count %>"
            ></span>
          <% end %>

          <ul class="list-inline tags">
            <% q.tag_list.each do |tag| %>
              <li>
                <%= link_to "##{tag}", questions_path(:tag_filter => tag), :class => "label label-primary" %>
              </li>
            <% end %>
          </ul>
        </footer>
      </article>
    </li>
  <% end %>
</ul>
<footer class="container text-center col-xs-12">
  <%= will_paginate @questions %>
</footer>

app/views/questions/new.html.erb
<%= render 'form',
  :url => questions_path,
  :method => 'post',
  :back => questions_path
%>

app/views/questions/show.html.erb
<section class="panel panel-default">
  <hr />
  <blockquote>
    <em class="lead"><%= @question.description %></em>
  </blockquote>
  <footer class="clearfix panel-footer text-center">
    <%= gravatar_image_tag @question.user.email,
      :alt => @question.user.email,
      :class => 'img-circle pull-left',
      :rel => 'tooltip',
      'data-toggle' => 'tooltip',
      'data-placement' => 'bottom',
      :title => '',
      'data-original-title' => @question.user.username,
      :gravatar => { :secure => true, :size => 30 }
    %>

    <% like_config = like_or_dislike(@question) %>
    <%= link_to(like_config[:path], :method => like_config[:method],
      :class => "pull-right like #{like_config[:class]}") do %>
      <span
        class="glyphicon glyphicon-heart"
        rel="tooltip"
        data-toggle="tooltip"
        data-placement="bottom"
        title=""
        data-original-title="<%= @question.likes.count %>"
      ></span>
    <% end %>

    <ul class="list-inline tags">
      <% @question.tag_list.each do |tag| %>
        <li>
          <%= link_to "##{tag}", questions_path(:tag_filter => tag), :class => "label label-primary" %>
        </li>
      <% end %>
    </ul>
  </footer>
</section>

<% if @question.user == current_user %>
  <section>
    <%= link_to edit_question_path(@question),
      :class => 'btn btn-info btn-sm pull-left',
      :style => 'margin-right:3px;' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      <span>Edit</span>
    <% end %>

    <%= button_to(@user, :method => :delete,
      :class => 'btn btn-danger btn-sm',
      :onclick => "if(!confirm('Are you sure?')){event.preventDefault(); return false;}",
      :alt => 'Remove User') do %>
      <span class="glyphicon glyphicon-trash"></span>
      <span>Remove</span>
    <% end %>
  </section>
<% end %>